@extends('admin.layout')
  @section('title', 'Projects')
  @section('page-title', 'Projects')
  @section('content')
  <div class="space-y-4">
    <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-3"><div class="relative flex-1"><svg class="absolute left-3 top-1/2 -translate-y-1/2 text-paragraph w-[15px] h-[15px]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg><input type="text" placeholder="Search by name, user, or room…" class="w-full bg-background rounded-lg pl-9 pr-4 py-2 text-sm font-sans text-foreground placeholder:text-paragraph focus:outline-none focus:border-primary border border-border/10"></div><div class="flex items-center gap-1.5 flex-wrap">@foreach(['All','Draft','Estimated','Completed'] as $status)<button class="px-3 py-1.5 rounded-lg text-xs font-sans font-medium {{ $loop->first ? 'bg-primary text-primary-foreground' : 'text-paragraph hover:text-foreground hover:bg-muted' }}">{{ $status }}</button>@endforeach</div></div>
    
    <div class="hidden sm:block bg-card rounded-[10px] overflow-hidden border border-border/10">
      <div class="flex items-center justify-between px-5 py-4"><h3 class="font-serif text-foreground text-base">Projects</h3></div>
      <div class="overflow-x-auto"><table class="w-full"><thead><tr class="border-b border-border/10"><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">ID</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Project Name</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">User</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Room</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Area</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Cost</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Status</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Actions</th></tr></thead><tbody>@forelse($projects as $project)
<tr class="hover:bg-muted/50 transition-colors duration-200 border-b border-border/5"><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#{{ $project->id }}</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">{{ $project->name }}</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">{{ $project->user->name ?? 'N/A' }}</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">{{ $project->room_type }}</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">{{ $project->area_size }} m²</span></td><td class="px-5 py-3 text-sm font-sans text-foreground" x-data="{ status: '{{ ucfirst($project->status) }}' }" x-text="status === 'Completed' ? '$' + Math.round({{ $project->area_size }} * 500) : '—'"></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium" :class="{ 'bg-status-active/15 text-status-active': '{{ $project->status }}' === 'completed', 'bg-status-warning/15 text-status-warning': '{{ $project->status }}' === 'estimated', 'bg-muted text-muted-foreground': '{{ $project->status }}' === 'draft' }">{{ ucfirst($project->status) }}</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="/admin/projects/{{ $project->id }}/edit" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><form method="POST" action="/admin/projects/{{ $project->id }}" style="display:inline" onsubmit="return confirm('Are you sure?')">@csrf @method('DELETE')<button type="submit" class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></form></div></td></tr>
@empty
<tr><td colspan="8" class="px-5 py-3 text-center text-paragraph">No projects found</td></tr>
@endforelse</tbody></table></div>
    </div>
  </div>
  @endsection
  
