<?php

namespace App\Exports;

use App\Models\Project;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithColumnWidths;
use Maatwebsite\Excel\Concerns\WithTitle;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;

class RabExport implements FromArray, WithStyles, WithColumnWidths, WithTitle
{
    public function __construct(
        protected Project $project,
        protected array $rab,
    ) {}

    public function title(): string
    {
        return 'RAB';
    }

    public function columnWidths(): array
    {
        return [
            'A' => 6,
            'B' => 35,
            'C' => 10,
            'D' => 8,
            'E' => 20,
            'F' => 20,
            'G' => 22,
            'H' => 22,
        ];
    }

    public function array(): array
    {
        $rows = [];

        // Header project
        $rows[] = ['RENCANA ANGGARAN BIAYA (RAB)', '', '', '', '', '', '', ''];
        $rows[] = ['Proyek: ' . $this->project->name, '', '', '', '', '', '', ''];
        $rows[] = ['Lokasi: ' . ucfirst($this->project->location ?? '-'), '', '', '', '', 'Tanggal:', now()->format('d M Y'), ''];
        $rows[] = ['', '', '', '', '', '', '', ''];

        // Table headers
        $rows[] = ['No', 'Item Pekerjaan', 'Volume', 'Sat.', 'Harga Satuan (Min)', 'Harga Satuan (Max)', 'Total Min', 'Total Max'];

        $no = 1;
        foreach ($this->rab['items'] as $item) {
            // Category row
            $rows[] = ['', 'PEKERJAAN ' . strtoupper($item['label']), '', '', '', '', '', ''];

            // Data row
            $rows[] = [
                $no++,
                $item['label'],
                number_format($item['area'], 2),
                'm²',
                'Rp ' . number_format($item['unit_price_min'], 0, ',', '.'),
                'Rp ' . number_format($item['unit_price_max'], 0, ',', '.'),
                'Rp ' . number_format($item['total_min'], 0, ',', '.'),
                'Rp ' . number_format($item['total_max'], 0, ',', '.'),
            ];

            // Subtotal row
            $rows[] = [
                '', '', '', '', '', 'SUBTOTAL',
                'Rp ' . number_format($item['total_min'], 0, ',', '.'),
                'Rp ' . number_format($item['total_max'], 0, ',', '.'),
            ];

            // Empty row
            $rows[] = ['', '', '', '', '', '', '', ''];
        }

        // Grand total
        $rows[] = [
            '', '', '', '', '', 'TOTAL RAB',
            'Rp ' . number_format($this->rab['grand_min'], 0, ',', '.'),
            'Rp ' . number_format($this->rab['grand_max'], 0, ',', '.'),
        ];

        // Disclaimer
        $rows[] = ['', '', '', '', '', '', '', ''];
        $rows[] = ['* Estimasi berdasarkan harga pasar rata-rata. Harga aktual dapat berbeda tergantung kondisi lapangan.', '', '', '', '', '', '', ''];
        $rows[] = ['* Generated by RenovaSim — ' . now()->format('d M Y H:i'), '', '', '', '', '', '', ''];

        return $rows;
    }

    public function styles(Worksheet $sheet): array
    {
        $green  = '8BA023';
        $lightG = 'F0F4E8';
        $gray   = 'F5F5F5';

        // Title
        $sheet->mergeCells('A1:H1');
        $sheet->mergeCells('A2:H2');
        $sheet->mergeCells('A3:E3');

        return [
            1 => [
                'font'      => ['bold' => true, 'size' => 14, 'color' => ['rgb' => $green]],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            2 => [
                'font'      => ['bold' => true, 'size' => 11],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
            5 => [
                'font'      => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
                'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => $green]],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
                'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN]],
            ],
        ];
    }
}
