@extends('admin.layout')
  @section('title', 'Dashboard')
  @section('page-title', 'Dashboard')
  @section('content')
  <div class="space-y-4">
    <div><h1 class="text-2xl font-serif text-foreground">Welcome back 👋</h1><p class="text-sm text-muted-foreground mt-1">{{ now()->format('l, F j, Y') }}</p></div>
    <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
      <div class="relative bg-card rounded-[14px] border border-border/10 flex flex-col min-h-[250px] overflow-hidden transition-all duration-200 hover:shadow-xl hover:border-border/20"><div class="absolute top-0 left-0 right-0 h-[3px] rounded-t-[14px] bg-primary-accent"></div><div class="px-6 pt-7 pb-3 flex-1"><p class="text-[10px] uppercase tracking-[0.15em] font-sans text-paragraph">Total Users</p><div class="flex items-end gap-3 mt-2"><p class="text-[2.75rem] leading-none font-serif text-foreground">75.782</p><span class="mb-1 inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold bg-primary-accent/20 text-primary-accent">↗ 2%</span></div><p class="text-[11px] font-sans mt-2.5 text-paragraph">+24.635 users from last month</p><div class="flex items-center gap-4 mt-4 pt-3 border-t border-border/10"><div><p class="text-[9px] uppercase tracking-widest text-paragraph">This month</p><p class="text-sm font-serif text-foreground mt-0.5">+24.635</p></div><div><p class="text-[9px] uppercase tracking-widest text-paragraph">Last month</p><p class="text-sm font-serif text-foreground mt-0.5">51.147</p></div></div></div><div class="w-full h-[100px]"><canvas id="totalUsersSpark"></canvas></div></div>
      <div class="relative bg-card rounded-[14px] border border-border/10 flex flex-col min-h-[250px] overflow-hidden transition-all duration-200 hover:shadow-xl hover:border-border/20"><div class="absolute top-0 left-0 right-0 h-[3px] rounded-t-[14px] bg-primary-accent"></div><div class="px-6 pt-7"><p class="text-[10px] uppercase tracking-[0.15em] font-sans text-paragraph">Active Users</p><div class="flex items-end gap-3 mt-2"><p class="text-[2.75rem] leading-none font-serif text-foreground">25.782</p><span class="mb-1 inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold bg-destructive/15 text-destructive">↘ -1%</span></div></div><div class="flex-1 flex items-center justify-between px-6 py-3"><div class="relative shrink-0"><svg width="148" height="148" viewBox="0 0 148 148"><defs><linearGradient id="gaugeGrad" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stop-color="#8BA023" stop-opacity="0.7"/><stop offset="100%" stop-color="#8BA023"/></linearGradient><filter id="gaugeGlow" x="-20%" y="-20%" width="140%" height="140%"><feGaussianBlur stdDeviation="3" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><circle cx="74" cy="74" r="66" fill="none" stroke="currentColor" class="text-primary-accent" stroke-width="1" stroke-opacity="0.12"/><circle cx="74" cy="74" r="56" fill="none" stroke="currentColor" class="text-border" stroke-width="14" stroke-linecap="round" stroke-dasharray="237.6 351.9" transform="rotate(135 74 74)"/><circle cx="74" cy="74" r="56" fill="none" stroke="currentColor" class="text-paragraph" stroke-width="14" stroke-linecap="round" stroke-opacity="0.2" stroke-dasharray="52.3 351.9" stroke-dashoffset="-185.2" transform="rotate(135 74 74)"/><circle cx="74" cy="74" r="56" fill="none" stroke="url(#gaugeGrad)" stroke-width="14" stroke-linecap="round" filter="url(#gaugeGlow)" stroke-dasharray="185.2 351.9" transform="rotate(135 74 74)"/></svg><div class="absolute inset-0 flex flex-col items-center justify-center"><span class="text-[1.6rem] font-serif text-foreground leading-none">78%</span><span class="text-[9px] uppercase tracking-wider text-paragraph mt-1">active rate</span></div></div><div class="flex flex-col gap-3 ml-2"><div><p class="text-[9px] uppercase tracking-widest text-paragraph">Active</p><p class="text-sm font-serif text-foreground">25.782</p></div><div><p class="text-[9px] uppercase tracking-widest text-paragraph">Inactive</p><p class="text-sm font-serif text-foreground">7.259</p></div><div><p class="text-[9px] uppercase tracking-widest text-paragraph">Total</p><p class="text-sm font-serif text-foreground">33.041</p></div></div></div></div>
      <div class="relative bg-card rounded-[14px] border border-border/10 flex flex-col min-h-[250px] overflow-hidden transition-all duration-200 hover:shadow-xl hover:border-border/20"><div class="absolute top-0 left-0 right-0 h-[3px] rounded-t-[14px] bg-primary-accent"></div><div class="px-6 pt-7 pb-3 flex-1"><div class="flex items-start justify-between"><p class="text-[10px] uppercase tracking-[0.15em] font-sans text-paragraph">New Clients</p><button class="text-[10px] text-paragraph border border-border/20 rounded-full px-2 py-0.5">Last 7 days ▾</button></div><div class="flex items-end gap-3 mt-2"><p class="text-[2.75rem] leading-none font-serif text-foreground">6.782</p><span class="mb-1 inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold bg-paragraph/20 text-paragraph">0% —</span></div><p class="text-[11px] font-sans mt-2.5 text-paragraph">Compared to last 7 days</p></div><div class="w-full h-[100px]"><canvas id="clientsSpark"></canvas></div></div>
      <div class="relative bg-card rounded-[14px] border border-border/10 flex flex-col min-h-[250px] overflow-hidden transition-all duration-200 hover:shadow-xl hover:border-border/20"><div class="absolute top-0 left-0 right-0 h-[3px] rounded-t-[14px] bg-primary-accent"></div><div class="px-6 pt-7 pb-3 flex-1"><div class="flex items-start justify-between"><p class="text-[10px] uppercase tracking-[0.15em] font-sans text-paragraph">Active Subscriptions</p><button class="text-[10px] text-paragraph border border-border/20 rounded-full px-2 py-0.5">Last 7 days ▾</button></div><div class="flex items-end gap-3 mt-2"><p class="text-[2.75rem] leading-none font-serif text-foreground">2.986</p><span class="mb-1 inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold bg-primary-accent/20 text-primary-accent">4% ↗</span></div><p class="text-[11px] font-sans mt-2.5 text-paragraph">Compared to last 7 days</p></div><div class="w-full h-[100px] px-4"><canvas id="subscriptionsSpark"></canvas></div></div>
    </div>
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-4">
      @foreach([['Total Users','120','↑ 12% this month'],['Projects','67','↑ 8 new this week'],['Materials','240','Across 8 categories'],['Active Plans','3','Free · Smart · Pro']] as $stat)
      <div class="relative bg-card rounded-[14px] p-6 border border-border/10 overflow-hidden transition-all duration-200 hover:shadow-lg hover:border-border/20"><p class="text-[9px] uppercase tracking-[0.18em] font-sans text-paragraph">{{ $stat[0] }}</p><p class="text-[2.2rem] leading-none font-serif text-foreground mt-3">{{ $stat[1] }}</p><p class="text-[11px] font-sans mt-2 text-paragraph">{{ $stat[2] }}</p></div>
      @endforeach
    </div>
    <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
      <div class="lg:col-span-2 bg-card rounded-[14px] border border-border/10 p-6 transition-all hover:shadow-lg"><div class="flex items-center justify-between mb-5"><div><h3 class="font-serif text-base text-foreground">Projects Over Time</h3><p class="text-[10px] text-paragraph mt-0.5 uppercase tracking-widest">Jan – Aug 2026</p></div><div class="flex items-center gap-1.5 text-[11px] font-semibold px-2.5 py-1 rounded-full bg-primary-accent/20 text-primary-accent">↗ +34% vs last year</div></div><div class="h-[240px]"><canvas id="projectsChart"></canvas></div></div>
      <div class="bg-card rounded-[14px] border border-border/10 p-6 flex flex-col transition-all hover:shadow-lg"><div class="mb-4"><h3 class="font-serif text-base text-foreground">Users by Plan</h3><p class="text-[10px] text-paragraph mt-0.5 uppercase tracking-widest">Distribution</p></div><div class="relative flex items-center justify-center h-[180px]"><canvas id="plansChart"></canvas><div class="absolute inset-0 flex flex-col items-center justify-center pointer-events-none"><span class="text-[1.8rem] font-serif text-foreground leading-none">120</span><span class="text-[10px] text-paragraph mt-1 uppercase tracking-wider">users</span></div></div><div class="mt-auto pt-4 space-y-2.5 border-t border-border/10">@foreach([['Free',60],['Smart',30],['Pro',10]] as $plan)<div class="flex items-center justify-between"><span class="text-xs text-paragraph">{{ $plan[0] }}</span><span class="text-xs font-medium text-foreground">{{ $plan[1] }}%</span></div>@endforeach</div></div>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <div class="bg-card rounded-[14px] border border-border/10 p-6 transition-all hover:shadow-lg"><div class="mb-5"><h3 class="font-serif text-base text-foreground">Top Materials Used</h3><p class="text-[10px] text-paragraph mt-0.5 uppercase tracking-widest">By project count</p></div><div class="h-[220px]"><canvas id="materialsChart"></canvas></div></div>
      <div class="bg-card rounded-[14px] border border-border/10 p-6 transition-all hover:shadow-lg"><div class="mb-5"><h3 class="font-serif text-base text-foreground">Cost Estimation Range</h3><p class="text-[10px] text-paragraph mt-0.5 uppercase tracking-widest">Projects per range</p></div><div class="h-[220px]"><canvas id="costChart"></canvas></div></div>
    </div>
    @php($activities=[['AP','Andi Pratama','Created a new project','In progress','2 min ago','Living Room'],['SD','Sari Dewi','Updated plan pricing','Done','1 hour ago','Smart Plan'],['BS','Budi Santoso','Added new material','In progress','3 hours ago','Vinyl Flooring'],['RW','Rina Wati','Registered as new user','Done','Yesterday','Free Plan'],['FH','Fajar Hidayat','Updated feature list','In progress','2 days ago','Pro Plan']])
    <div class="bg-card rounded-[14px] border border-border/10 overflow-hidden transition-all hover:shadow-lg"><div class="px-6 pt-6 pb-4 flex items-center justify-between border-b border-border/10"><div><h3 class="font-serif text-base text-foreground">Recent Activity</h3><p class="text-[10px] text-paragraph mt-0.5 uppercase tracking-widest">Last 5 events</p></div><span class="text-[10px] px-2.5 py-1 rounded-full border border-border/20 text-paragraph">View all →</span></div><div class="hidden sm:grid sm:grid-cols-[2fr_2fr_1fr_1fr_1fr] gap-3 px-6 py-2.5 text-[9px] uppercase tracking-[0.18em] text-paragraph bg-muted/40"><span>User</span><span>Action</span><span>Status</span><span>Time</span><span class="text-right">Detail</span></div>@foreach($activities as $a)<div class="flex items-center gap-3 px-6 py-3.5 sm:grid sm:grid-cols-[2fr_2fr_1fr_1fr_1fr] sm:items-center border-b border-border/5"><div class="flex items-center gap-3 min-w-0"><div class="w-9 h-9 rounded-full shrink-0 flex items-center justify-center text-[11px] font-semibold text-foreground bg-primary-accent">{{ $a[0] }}</div><span class="text-sm text-foreground truncate font-medium">{{ $a[1] }}</span></div><span class="hidden sm:block text-[13px] text-paragraph truncate">{{ $a[2] }}</span><span class="hidden sm:inline-flex px-2.5 py-1 rounded-full text-[10px] font-semibold {{ $a[3] === 'Done' ? 'bg-primary-accent/20 text-primary-accent' : 'bg-status-warning/15 text-status-warning' }}">{{ $a[3] }}</span><span class="text-[11px] text-paragraph shrink-0 ml-auto sm:ml-0">{{ $a[4] }}</span><span class="hidden sm:block text-[11px] text-paragraph text-right truncate">{{ $a[5] }}</span></div>@endforeach</div>
  </div>
  @endsection
  @push('scripts')
  <script>
  document.addEventListener('DOMContentLoaded', function () {
    const grid = 'rgba(245,245,245,0.05)';
    const tick = '#838383';
    const accent = '#8BA023';
    const sparkOptions = { responsive:true, maintainAspectRatio:false, plugins:{legend:{display:false}}, scales:{x:{display:false}, y:{display:false}}, elements:{point:{radius:0}} };
    new Chart(document.getElementById('totalUsersSpark'), { type:'line', data:{ labels:Array.from({length:20}, function(_, i) { return i; }), datasets:[{ data:[20,18,25,22,30,24,35,28,22,32,26,38,30,28,34,40,36,45,42,50], borderColor:accent, backgroundColor:'rgba(139,160,35,0.08)', fill:true, tension:.4 }] }, options:sparkOptions });
    new Chart(document.getElementById('clientsSpark'), { type:'line', data:{ labels:['1','2','3','4','5','6','7'], datasets:[{ data:[10,14,8,18,12,20,15], borderColor:accent, backgroundColor:'rgba(139,160,35,0.08)', fill:true, tension:.4 }] }, options:sparkOptions });
    new Chart(document.getElementById('subscriptionsSpark'), { type:'bar', data:{ labels:['1','2','3','4','5','6','7'], datasets:[{ data:[8,12,6,14,10,16,9], backgroundColor:accent, borderRadius:4 }] }, options:sparkOptions });
    new Chart(document.getElementById('projectsChart'), { type:'line', data:{ labels:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug'], datasets:[{ data:[3,7,5,12,8,15,11,18], borderColor:'#8BA023', backgroundColor:'rgba(139,160,35,0.08)', fill:true, tension:0.4 }] }, options:{ responsive:true, maintainAspectRatio:false, plugins:{ legend:{ display:false } }, scales:{ x:{ grid:{ color:grid }, ticks:{ color:tick } }, y:{ grid:{ color:grid }, ticks:{ color:tick } } } } });
    new Chart(document.getElementById('plansChart'), { type:'doughnut', data:{ labels:['Free','Smart','Pro'], datasets:[{ data:[60,30,10], backgroundColor:['#838383','#8BA023','#d4941a'], borderWidth:0 }] }, options:{ responsive:true, maintainAspectRatio:false, cutout:'65%', plugins:{ legend:{ display:false } } } });
    new Chart(document.getElementById('materialsChart'), { type:'bar', data:{ labels:['Vinyl Flooring','Ceramic Tile','Wall Paint','Plywood','Gypsum Board'], datasets:[{ data:[42,38,35,28,22], backgroundColor:'#8BA023', borderRadius:5 }] }, options:{ indexAxis:'y', responsive:true, maintainAspectRatio:false, plugins:{ legend:{ display:false } }, scales:{ x:{ grid:{ color:grid }, ticks:{ color:tick } }, y:{ grid:{ color:grid }, ticks:{ color:tick } } } } });
    new Chart(document.getElementById('costChart'), { type:'bar', data:{ labels:['< 5jt','5–20jt','20–50jt','> 50jt'], datasets:[{ data:[12,28,18,9], backgroundColor:'#8BA023', borderRadius:5 }] }, options:{ responsive:true, maintainAspectRatio:false, plugins:{ legend:{ display:false } }, scales:{ x:{ grid:{ color:grid }, ticks:{ color:tick } }, y:{ grid:{ color:grid }, ticks:{ color:tick } } } } });
  });
  </script>
  @endpush
  
