@extends('admin.layout')
  @section('title', 'Materials')
  @section('page-title', 'Materials')
  @section('content')
  <div class="space-y-4">
    
    
    <div class="hidden sm:block bg-card rounded-[10px] overflow-hidden border border-border/10">
      <div class="flex items-center justify-between px-5 py-4"><h3 class="font-serif text-foreground text-base">Materials</h3><a href="/admin/materials/create" class="px-3 py-1.5 rounded-lg text-xs font-sans font-medium bg-foreground text-background">+ Add Material</a></div>
      <div class="overflow-x-auto"><table class="w-full"><thead><tr class="border-b border-border/10"><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">ID</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Name</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Category</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Price/Unit</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Unit</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Status</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Actions</th></tr></thead><tbody><tr class="hover:bg-muted/50 transition-colors duration-200 border-b border-border/5"><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#1</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Ceramic Tile</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">Flooring</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">$25</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">m²</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-active/15 text-status-active">Active</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="#" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><button class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></div></td></tr>
<tr class="hover:bg-muted/50 transition-colors duration-200 border-b border-border/5"><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#2</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Oak Hardwood</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">Flooring</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">$45</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">m²</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-active/15 text-status-active">Active</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="#" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><button class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></div></td></tr>
<tr class="hover:bg-muted/50 transition-colors duration-200 "><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#3</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Granite Countertop</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">Surfaces</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">$80</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">m²</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-active/15 text-status-active">Active</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="#" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><button class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></div></td></tr></tbody></table></div>
    </div>
  </div>
  @endsection
  
