@extends('admin.layout')
  @section('title', 'Users')
  @section('page-title', 'Users')
  @section('content')
  <div class="space-y-4">
    <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-3"><div class="relative flex-1"><svg class="absolute left-3 top-1/2 -translate-y-1/2 text-paragraph w-[15px] h-[15px]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg><input type="text" placeholder="Search by name or email…" class="w-full bg-background rounded-lg pl-9 pr-4 py-2 text-sm font-sans text-foreground placeholder:text-paragraph focus:outline-none focus:border-primary border border-border/10"></div><a href="/admin/users/create" class="ml-1 flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-sans font-medium bg-foreground text-background"><svg class="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg> Add User</a></div>
    <div class="hidden sm:block bg-card rounded-[10px] overflow-hidden border border-border/10">
      <div class="flex items-center justify-between px-5 py-4"><h3 class="font-serif text-foreground text-base">Users</h3></div>
      <div class="overflow-x-auto"><table class="w-full"><thead><tr class="border-b border-border/10"><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">ID</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Username</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Email</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Created</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Actions</th></tr></thead><tbody>@forelse($users as $user)<tr class="hover:bg-muted/50 transition-colors duration-200 border-b border-border/5"><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#{{ $user->id }}</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">{{ $user->username }}</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">{{ $user->email }}</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">{{ $user->created_at->format('Y-m-d') }}</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="/admin/users/{{ $user->id }}/edit" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><form method="POST" action="/admin/users/{{ $user->id }}" style="display:inline" onsubmit="return confirm('Are you sure?');">@csrf @method('DELETE')<button type="submit" class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></form></div></td></tr>@empty<tr><td colspan="5" class="px-5 py-8 text-center text-paragraph">No users found</td></tr>@endforelse</tbody></table></div>
      @if($users->hasPages())<div class="px-5 py-4 border-t border-border/10 flex justify-center">{{ $users->links() }}</div>@endif
    </div>
  </div>
  @endsection
  
