@extends('admin.layout')
  @section('title', 'Materials')
  @section('page-title', 'Materials')
  @section('content')
  <div class="space-y-4">
    <div class="hidden sm:block bg-card rounded-[10px] overflow-hidden border border-border/10">
      <div class="flex items-center justify-between px-5 py-4"><h3 class="font-serif text-foreground text-base">Materials</h3><a href="/admin/materials/create" class="px-3 py-1.5 rounded-lg text-xs font-sans font-medium bg-foreground text-background">+ Add Material</a></div>
      <div class="overflow-x-auto"><table class="w-full"><thead><tr class="border-b border-border/10"><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">ID</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Name</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Category</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Price/Unit</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Unit</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Actions</th></tr></thead><tbody>@forelse($materials as $material)<tr class="hover:bg-muted/50 transition-colors duration-200 border-b border-border/5"><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#{{ $material->id }}</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">{{ $material->name }}</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">{{ $material->category }}</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">${{ $material->price_per_unit }}</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">{{ $material->unit }}</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="/admin/materials/{{ $material->id }}/edit" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><form method="POST" action="/admin/materials/{{ $material->id }}" style="display:inline" onsubmit="return confirm('Are you sure?');">@csrf @method('DELETE')<button type="submit" class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></form></div></td></tr>@empty<tr><td colspan="6" class="px-5 py-8 text-center text-paragraph">No materials found</td></tr>@endforelse</tbody></table></div>
    </div>
  </div>
  @endsection
