@extends('admin.layout')
  @section('title', 'Projects')
  @section('page-title', 'Projects')
  @section('content')
  <div class="space-y-4">
    <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-3"><div class="relative flex-1"><svg class="absolute left-3 top-1/2 -translate-y-1/2 text-paragraph w-[15px] h-[15px]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg><input type="text" placeholder="Search by name, user, or room…" class="w-full bg-background rounded-lg pl-9 pr-4 py-2 text-sm font-sans text-foreground placeholder:text-paragraph focus:outline-none focus:border-primary border border-border/10"></div><div class="flex items-center gap-1.5 flex-wrap">@foreach(['All','Draft','Estimated','Completed'] as $status)<button class="px-3 py-1.5 rounded-lg text-xs font-sans font-medium {{ $loop->first ? 'bg-primary text-primary-foreground' : 'text-paragraph hover:text-foreground hover:bg-muted' }}">{{ $status }}</button>@endforeach</div></div>
    
    <div class="hidden sm:block bg-card rounded-[10px] overflow-hidden border border-border/10">
      <div class="flex items-center justify-between px-5 py-4"><h3 class="font-serif text-foreground text-base">Projects</h3></div>
      <div class="overflow-x-auto"><table class="w-full"><thead><tr class="border-b border-border/10"><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">ID</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Project Name</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">User</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Room</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Area</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Cost</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Status</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Actions</th></tr></thead><tbody><tr class="hover:bg-muted/50 transition-colors duration-200 border-b border-border/5"><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#1</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Kitchen Remodel</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">John Doe</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Kitchen</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">25 m²</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">$12,400</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-active/15 text-status-active">Completed</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="#" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><button class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></div></td></tr>
<tr class="hover:bg-muted/50 transition-colors duration-200 border-b border-border/5"><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#2</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Bathroom Update</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">Jane Smith</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Bathroom</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">12 m²</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">$6,800</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-warning/15 text-status-warning">Estimated</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="#" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><button class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></div></td></tr>
<tr class="hover:bg-muted/50 transition-colors duration-200 "><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#3</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Living Room</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">Ali Mammadov</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Living</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">35 m²</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">—</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-muted text-muted-foreground">Draft</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="#" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><button class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></div></td></tr></tbody></table></div>
    </div>
  </div>
  @endsection
  
