@extends('admin.layout')
  @section('title', 'Project Detail')
  @section('page-title', 'Project Detail')
  @section('content')
  <div class="space-y-4">
    <div class="bg-card rounded-[14px] border border-border/10 p-6"><div class="flex items-start justify-between"><div><h2 class="font-serif text-2xl text-foreground">Kitchen Remodel</h2><p class="text-sm text-paragraph mt-1">John Doe · Kitchen · 25 m²</p></div><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-active/15 text-status-active">Completed</span></div><div class="grid grid-cols-1 sm:grid-cols-3 gap-4 mt-6"><div><p class="text-[10px] uppercase tracking-widest text-paragraph">Estimated Cost</p><p class="text-2xl font-serif text-foreground mt-1">$12,400</p></div><div><p class="text-[10px] uppercase tracking-widest text-paragraph">Room</p><p class="text-2xl font-serif text-foreground mt-1">Kitchen</p></div><div><p class="text-[10px] uppercase tracking-widest text-paragraph">Area</p><p class="text-2xl font-serif text-foreground mt-1">25 m²</p></div></div></div>
    <div class="bg-card rounded-[10px] overflow-hidden border border-border/10"><div class="px-5 py-4"><h3 class="font-serif text-foreground text-base">Material Breakdown</h3></div><table class="w-full"><thead><tr class="border-b border-border/10"><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Material</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Category</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Quantity</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Unit Price</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Total</th></tr></thead><tbody>@foreach([['Ceramic Tile','Flooring','18 m²','$25','$450'],['Granite Countertop','Surfaces','4 m²','$80','$320'],['LED Panel Light','Lighting','8 pcs','$35','$280']] as $row)<tr class="border-b border-border/5"><td class="px-5 py-3 text-sm font-sans text-foreground">{{ $row[0] }}</td><td class="px-5 py-3 text-sm font-sans text-paragraph">{{ $row[1] }}</td><td class="px-5 py-3 text-sm font-sans text-paragraph">{{ $row[2] }}</td><td class="px-5 py-3 text-sm font-sans text-foreground">{{ $row[3] }}</td><td class="px-5 py-3 text-sm font-sans text-foreground">{{ $row[4] }}</td></tr>@endforeach</tbody></table></div>
  </div>
  @endsection
  
