@extends('admin.layout')
  @section('title', 'Users')
  @section('page-title', 'Users')
  @section('content')
  <div class="space-y-4">
    <div class="flex flex-col gap-2 sm:flex-row sm:items-center sm:gap-3"><div class="relative flex-1"><svg class="absolute left-3 top-1/2 -translate-y-1/2 text-paragraph w-[15px] h-[15px]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg><input type="text" placeholder="Search by name or email…" class="w-full bg-background rounded-lg pl-9 pr-4 py-2 text-sm font-sans text-foreground placeholder:text-paragraph focus:outline-none focus:border-primary border border-border/10"></div><div class="flex items-center gap-1.5 flex-wrap">@foreach(['All','Free','Smart','Pro'] as $plan)<button class="px-3 py-1.5 rounded-lg text-xs font-sans font-medium {{ $loop->first ? 'bg-primary text-primary-foreground' : 'text-paragraph hover:text-foreground hover:bg-muted' }}">{{ $plan }}</button>@endforeach<a href="/admin/users/create" class="ml-1 flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-sans font-medium bg-foreground text-background"><svg class="w-3 h-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg> Add User</a></div></div>
    @php($users=[['1','John Doe','john@mail.com','Pro','2024-01-15','Active'],['2','Jane Smith','jane@mail.com','Smart','2024-02-20','Active'],['3','Ali Mammadov','ali@mail.com','Free','2024-03-10','Active'],['4','Sara Johnson','sara@mail.com','Smart','2024-03-25','Active'],['5','Mike Wilson','mike@mail.com','Pro','2024-04-01','Active']])<div class="flex flex-col gap-3 sm:hidden">@foreach($users as $u)<div class="bg-card rounded-[12px] border border-border/10 p-4 space-y-3"><div class="flex items-center justify-between"><div><p class="text-sm font-medium text-foreground leading-tight">{{ $u[1] }}</p><p class="text-[11px] text-paragraph">{{ $u[2] }}</p></div><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-active/15 text-status-active">{{ $u[5] }}</span></div><div class="grid grid-cols-3 gap-2 pt-2 border-t border-border/10 text-center"><div><p class="text-[9px] uppercase tracking-widest text-paragraph mb-0.5">ID</p><p class="text-xs font-medium text-foreground">#{{ $u[0] }}</p></div><div><p class="text-[9px] uppercase tracking-widest text-paragraph mb-0.5">Plan</p><p class="text-xs font-medium text-foreground">{{ $u[3] }}</p></div><div><p class="text-[9px] uppercase tracking-widest text-paragraph mb-0.5">Joined</p><p class="text-xs font-medium text-foreground">{{ $u[4] }}</p></div></div><div class="flex gap-2"><a href="#" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><button class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></div></div>@endforeach</div>
    <div class="hidden sm:block bg-card rounded-[10px] overflow-hidden border border-border/10">
      <div class="flex items-center justify-between px-5 py-4"><h3 class="font-serif text-foreground text-base">Users</h3><a href="/admin/users/create" class="px-3 py-1.5 rounded-lg text-xs font-sans font-medium bg-foreground text-background">+ Add User</a></div>
      <div class="overflow-x-auto"><table class="w-full"><thead><tr class="border-b border-border/10"><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">ID</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Name</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Email</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Plan</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Joined</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Status</th><th class="text-[10px] uppercase tracking-widest text-paragraph font-sans font-normal text-left px-5 py-3">Actions</th></tr></thead><tbody><tr class="hover:bg-muted/50 transition-colors duration-200 border-b border-border/5"><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#1</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">John Doe</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">john@mail.com</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-warning/15 text-status-warning">Pro</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">2024-01-15</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-active/15 text-status-active">Active</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="#" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><button class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></div></td></tr>
<tr class="hover:bg-muted/50 transition-colors duration-200 border-b border-border/5"><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#2</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Jane Smith</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">jane@mail.com</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-active/15 text-status-active">Smart</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">2024-02-20</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-active/15 text-status-active">Active</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="#" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><button class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></div></td></tr>
<tr class="hover:bg-muted/50 transition-colors duration-200 "><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">#3</span></td><td class="px-5 py-3 text-sm font-sans text-foreground">Ali Mammadov</td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">ali@mail.com</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-muted text-muted-foreground">Free</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="text-paragraph">2024-03-10</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><span class="px-2.5 py-0.5 rounded text-xs font-sans font-medium bg-status-active/15 text-status-active">Active</span></td><td class="px-5 py-3 text-sm font-sans text-foreground"><div class="flex gap-2"><a href="#" class="px-3 py-1 rounded text-xs font-sans font-medium bg-foreground text-background">Edit</a><button class="px-3 py-1 rounded text-xs font-sans font-medium bg-destructive/15 text-destructive">Delete</button></div></td></tr></tbody></table></div>
    </div>
  </div>
  @endsection
  
